# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.1].define(version: 2026_06_15_220907) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "pg_catalog.plpgsql"

  create_table "api_clients", force: :cascade do |t|
    t.string "api_key", null: false
    t.datetime "created_at", null: false
    t.string "name"
    t.datetime "updated_at", null: false
  end

  create_table "field_aliases", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.string "engineering_unit"
    t.string "enthasys_id"
    t.string "measurement_type"
    t.integer "relevance", default: 1, null: false
    t.integer "scada_measurement_id"
    t.string "station_id"
    t.string "station_type"
    t.datetime "updated_at", null: false
  end

  create_table "projects", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.string "geographical_site"
    t.string "geographical_site_description"
    t.datetime "geographical_site_file_date"
    t.string "meteo_data"
    t.string "meteo_data_description"
    t.datetime "meteo_data_file_date"
    t.string "project", null: false
    t.string "project_description"
    t.datetime "project_file_date"
    t.string "pvsyst_version"
    t.string "satelite_data"
    t.datetime "simulation_date", null: false
    t.string "simulation_hourly_values_from"
    t.string "simulation_hourly_values_to"
    t.string "simulation_variant"
    t.string "simulation_variant_description"
    t.datetime "simulation_variant_file_date"
    t.datetime "updated_at", null: false
  end

  create_table "pvsyst_simulations", force: :cascade do |t|
    t.float "beam_hor"
    t.datetime "created_at", null: false
    t.float "diff_hor"
    t.float "e_arr_mpp"
    t.float "e_arr_nom"
    t.float "e_array"
    t.float "e_grid"
    t.float "e_out_inv"
    t.float "g_inc_lss"
    t.float "glob_eff"
    t.float "glob_hor"
    t.float "glob_inc"
    t.float "iam_loss"
    t.float "il_oper"
    t.float "il_pmax"
    t.float "il_pmin"
    t.float "il_vmin"
    t.float "mis_loss"
    t.float "mod_qual"
    t.float "ohm_loss"
    t.integer "project_id"
    t.float "shd_loss"
    t.datetime "simulation_time", null: false
    t.float "slg_loss"
    t.float "t_amb"
    t.float "t_array"
    t.float "temp_lss"
    t.float "u_array"
    t.datetime "updated_at", null: false
    t.float "wind_vel"
  end

  create_table "pvsysts", force: :cascade do |t|
    t.string "altitude"
    t.float "array_soiling_losses_apr"
    t.float "array_soiling_losses_aug"
    t.float "array_soiling_losses_dec"
    t.float "array_soiling_losses_feb"
    t.float "array_soiling_losses_jan"
    t.float "array_soiling_losses_jul"
    t.float "array_soiling_losses_jun"
    t.float "array_soiling_losses_mar"
    t.float "array_soiling_losses_may"
    t.float "array_soiling_losses_nov"
    t.float "array_soiling_losses_oct"
    t.float "array_soiling_losses_sep"
    t.float "aux_loss_constant"
    t.float "aux_loss_power_thresh"
    t.float "avg_loss_fraction"
    t.integer "axis_azimuth"
    t.integer "axis_tilt"
    t.integer "cell_area"
    t.float "collector_width"
    t.string "country"
    t.datetime "created_at", null: false
    t.string "custom_params_def_manufacturer"
    t.float "field_orientation_axis_azimuth"
    t.float "field_orientation_axis_tilt"
    t.integer "global_power_nominal"
    t.integer "global_power_operating_cond"
    t.float "grid_power_limitation_active_power"
    t.float "grid_power_limitation_pnom_ratio"
    t.integer "grid_voltage"
    t.float "ground_cover_ratio"
    t.string "horizon"
    t.integer "i_mpp"
    t.float "incidence_effect_0"
    t.float "incidence_effect_30"
    t.float "incidence_effect_55"
    t.float "incidence_effect_60"
    t.float "incidence_effect_65"
    t.float "incidence_effect_70"
    t.float "incidence_effect_75"
    t.float "incidence_effect_80"
    t.float "incidence_effect_90"
    t.float "inductive_loss"
    t.float "inductive_loss_fraction"
    t.string "inverter_model"
    t.integer "inverter_unit_nom_power"
    t.integer "iron_loss"
    t.float "iron_loss_fraction"
    t.float "lc_collection_loss_apr"
    t.float "lc_collection_loss_aug"
    t.float "lc_collection_loss_dec"
    t.float "lc_collection_loss_feb"
    t.float "lc_collection_loss_jan"
    t.float "lc_collection_loss_jul"
    t.float "lc_collection_loss_jun"
    t.float "lc_collection_loss_mar"
    t.float "lc_collection_loss_may"
    t.float "lc_collection_loss_nov"
    t.float "lc_collection_loss_oct"
    t.float "lc_collection_loss_sep"
    t.float "ls_system_loss_apr"
    t.float "ls_system_loss_aug"
    t.float "ls_system_loss_dec"
    t.float "ls_system_loss_feb"
    t.float "ls_system_loss_jan"
    t.float "ls_system_loss_jul"
    t.float "ls_system_loss_jun"
    t.float "ls_system_loss_mar"
    t.float "ls_system_loss_may"
    t.float "ls_system_loss_nov"
    t.float "ls_system_loss_oct"
    t.float "ls_system_loss_sep"
    t.float "main_diffhor_apr"
    t.float "main_diffhor_aug"
    t.float "main_diffhor_dec"
    t.float "main_diffhor_feb"
    t.float "main_diffhor_jan"
    t.float "main_diffhor_jul"
    t.float "main_diffhor_jun"
    t.float "main_diffhor_mar"
    t.float "main_diffhor_may"
    t.float "main_diffhor_nov"
    t.float "main_diffhor_oct"
    t.float "main_diffhor_sep"
    t.float "main_diffhor_year"
    t.float "main_earray_apr"
    t.float "main_earray_aug"
    t.float "main_earray_dec"
    t.float "main_earray_feb"
    t.float "main_earray_jan"
    t.float "main_earray_jul"
    t.float "main_earray_jun"
    t.float "main_earray_mar"
    t.float "main_earray_may"
    t.float "main_earray_nov"
    t.float "main_earray_oct"
    t.float "main_earray_sep"
    t.float "main_earray_year"
    t.float "main_egrid_apr"
    t.float "main_egrid_aug"
    t.float "main_egrid_dec"
    t.float "main_egrid_feb"
    t.float "main_egrid_jan"
    t.float "main_egrid_jul"
    t.float "main_egrid_jun"
    t.float "main_egrid_mar"
    t.float "main_egrid_may"
    t.float "main_egrid_nov"
    t.float "main_egrid_oct"
    t.float "main_egrid_sep"
    t.float "main_egrid_year"
    t.float "main_globeff_apr"
    t.float "main_globeff_aug"
    t.float "main_globeff_dec"
    t.float "main_globeff_feb"
    t.float "main_globeff_jan"
    t.float "main_globeff_jul"
    t.float "main_globeff_jun"
    t.float "main_globeff_mar"
    t.float "main_globeff_may"
    t.float "main_globeff_nov"
    t.float "main_globeff_oct"
    t.float "main_globeff_sep"
    t.float "main_globeff_year"
    t.float "main_globhor_apr"
    t.float "main_globhor_aug"
    t.float "main_globhor_dec"
    t.float "main_globhor_feb"
    t.float "main_globhor_jan"
    t.float "main_globhor_jul"
    t.float "main_globhor_jun"
    t.float "main_globhor_mar"
    t.float "main_globhor_may"
    t.float "main_globhor_nov"
    t.float "main_globhor_oct"
    t.float "main_globhor_sep"
    t.float "main_globhor_year"
    t.float "main_globinc_apr"
    t.float "main_globinc_aug"
    t.float "main_globinc_dec"
    t.float "main_globinc_feb"
    t.float "main_globinc_jan"
    t.float "main_globinc_jul"
    t.float "main_globinc_jun"
    t.float "main_globinc_mar"
    t.float "main_globinc_may"
    t.float "main_globinc_nov"
    t.float "main_globinc_oct"
    t.float "main_globinc_sep"
    t.float "main_globinc_year"
    t.float "main_pr_apr"
    t.float "main_pr_aug"
    t.float "main_pr_dec"
    t.float "main_pr_feb"
    t.float "main_pr_jan"
    t.float "main_pr_jul"
    t.float "main_pr_jun"
    t.float "main_pr_mar"
    t.float "main_pr_may"
    t.float "main_pr_nov"
    t.float "main_pr_oct"
    t.float "main_pr_sep"
    t.float "main_pr_year"
    t.integer "main_simulation_aparent_energy"
    t.float "main_simulation_perf_ratio"
    t.integer "main_simulation_produced_energy"
    t.integer "main_simulation_specific_prod"
    t.string "main_system_inverter_model"
    t.float "main_system_inverter_pack"
    t.integer "main_system_pnom"
    t.integer "main_system_pnom_total"
    t.float "main_tamb_apr"
    t.float "main_tamb_aug"
    t.float "main_tamb_dec"
    t.float "main_tamb_feb"
    t.float "main_tamb_jan"
    t.float "main_tamb_jul"
    t.float "main_tamb_jun"
    t.float "main_tamb_mar"
    t.float "main_tamb_may"
    t.float "main_tamb_nov"
    t.float "main_tamb_oct"
    t.float "main_tamb_sep"
    t.float "main_tamb_year"
    t.integer "maximum_phi"
    t.integer "minimum_phi"
    t.string "models_used"
    t.integer "module_area"
    t.float "module_mismatch_loss_fraction"
    t.float "module_quality_loss_fraction"
    t.integer "module_unit_nom_power"
    t.string "near_shadings"
    t.float "night_aux_consumption"
    t.integer "number_of_trackers"
    t.string "operating_voltage"
    t.string "original_pysyst_db_manufacturer"
    t.float "performance_ratio_apr"
    t.float "performance_ratio_aug"
    t.float "performance_ratio_dec"
    t.float "performance_ratio_feb"
    t.float "performance_ratio_jan"
    t.float "performance_ratio_jul"
    t.float "performance_ratio_jun"
    t.float "performance_ratio_mar"
    t.float "performance_ratio_may"
    t.float "performance_ratio_nov"
    t.float "performance_ratio_oct"
    t.float "performance_ratio_sep"
    t.float "phi_limits"
    t.float "power_factor_cos"
    t.float "power_factor_phi"
    t.integer "project_id"
    t.integer "pv_array_number_modules"
    t.integer "pv_array_pnom_total"
    t.string "pv_module"
    t.integer "pv_modules_in_parallel"
    t.integer "pv_modules_in_series"
    t.string "pv_modules_model"
    t.string "pv_modules_pnom_total"
    t.string "situation_latitude"
    t.string "situation_longitude"
    t.float "strings_mismatch_loss_fraction"
    t.string "system_type"
    t.float "thermal_loss_factor_uc"
    t.float "thermal_loss_factor_uv"
    t.string "time_defined_as"
    t.string "time_zone"
    t.integer "total_pv_modules"
    t.float "tracker_spacing"
    t.string "tracking_algorithm"
    t.integer "u_mpp"
    t.datetime "updated_at", null: false
    t.float "user_needs_cos_phi"
    t.float "user_needs_unlimited_load"
    t.string "users_needs"
    t.integer "wires"
    t.float "wires_loss_fraction"
    t.float "wiring_ohmic_loss_fraction"
    t.float "wiring_ohmic_loss_global_array_res"
    t.float "yf_produced_useful_apr"
    t.float "yf_produced_useful_aug"
    t.float "yf_produced_useful_dec"
    t.float "yf_produced_useful_feb"
    t.float "yf_produced_useful_jan"
    t.float "yf_produced_useful_jul"
    t.float "yf_produced_useful_jun"
    t.float "yf_produced_useful_mar"
    t.float "yf_produced_useful_may"
    t.float "yf_produced_useful_nov"
    t.float "yf_produced_useful_oct"
    t.float "yf_produced_useful_sep"
    t.float "yf_produced_useful_year"
  end

  create_table "scada_events", force: :cascade do |t|
    t.string "cp_name"
    t.datetime "created_at", null: false
    t.datetime "date"
    t.string "measurement_apcode"
    t.string "measurement_source_id"
    t.string "site_id"
    t.datetime "updated_at", null: false
    t.float "val"
  end

  create_table "scada_measurement_sources", force: :cascade do |t|
    t.string "calc_period"
    t.integer "calc_time_span_count"
    t.string "calc_time_span_mode"
    t.string "calc_type_apcode"
    t.datetime "created_at", null: false
    t.datetime "date"
    t.string "eng_unit"
    t.boolean "manual_ingest"
    t.string "quality"
    t.string "range"
    t.integer "scada_measurement_id"
    t.datetime "updated_at", null: false
    t.string "uri"
    t.string "uuid"
    t.decimal "val"
    t.index ["scada_measurement_id"], name: "index_scada_measurement_sources_on_scada_measurement_id"
    t.index ["uuid"], name: "index_scada_measurement_sources_on_uuid", unique: true
  end

  create_table "scada_measurements", force: :cascade do |t|
    t.string "apcode"
    t.datetime "created_at", null: false
    t.string "measure_type_apcode"
    t.string "measure_type_data_type"
    t.string "measure_type_id"
    t.string "measure_type_name"
    t.string "measure_type_uri"
    t.string "mloc_id"
    t.boolean "monitor"
    t.string "monitor_eng_unit"
    t.string "monitor_status"
    t.string "monitor_uri"
    t.string "name"
    t.boolean "rcv"
    t.string "segment_apcode"
    t.integer "segment_apcode_idx"
    t.string "segment_id"
    t.string "segment_name"
    t.string "segment_uri"
    t.datetime "updated_at", null: false
    t.string "uuid"
    t.index ["measure_type_id"], name: "index_scada_measurements_on_measure_type_id"
    t.index ["segment_id"], name: "index_scada_measurements_on_segment_id"
    t.index ["uuid"], name: "index_scada_measurements_on_uuid", unique: true
  end

  create_table "scada_mlocs", force: :cascade do |t|
    t.string "apcode"
    t.datetime "created_at", null: false
    t.string "measurementTypeId"
    t.string "name"
    t.string "segment_id"
    t.string "sscode"
    t.datetime "updated_at", null: false
    t.string "uri"
    t.string "uuid"
  end

  create_table "scada_organizations", force: :cascade do |t|
    t.string "address"
    t.string "city"
    t.datetime "created_at", null: false
    t.string "name"
    t.string "state"
    t.datetime "updated_at", null: false
    t.string "uuid"
  end

  create_table "scada_segments", force: :cascade do |t|
    t.string "apcode"
    t.integer "apcode_idx"
    t.datetime "created_at", null: false
    t.string "name"
    t.string "site_id"
    t.datetime "updated_at", null: false
    t.string "uri"
    t.string "uuid"
    t.index ["id"], name: "index_scada_segments_on_id"
  end

  create_table "scada_sites", force: :cascade do |t|
    t.string "ac_load"
    t.string "activation_date"
    t.string "activation_date_nms"
    t.string "address"
    t.string "address_street"
    t.string "address_zip_code"
    t.string "admin_region"
    t.string "altitude"
    t.string "available_calculation_periods"
    t.string "cabin_group"
    t.string "cabin_kv_number"
    t.string "cabin_type"
    t.string "cabin_vendor"
    t.string "cabins_designs"
    t.string "city"
    t.string "contract"
    t.string "country"
    t.datetime "created_at", null: false
    t.string "crmid"
    t.string "district"
    t.string "dslam_code"
    t.string "dslam_network_ip_address"
    t.string "eett_code"
    t.string "enterprise_id"
    t.string "enterprise_name"
    t.string "grid_connected"
    t.string "information"
    t.string "installation_implementor"
    t.string "latitude"
    t.string "longitude"
    t.string "maintenance_contractor"
    t.string "maintenance_date"
    t.string "market_timezone"
    t.string "name"
    t.string "num_of_tcps"
    t.string "number_of_active_equipment"
    t.string "number_of_controllers"
    t.string "odss_active"
    t.string "odss_presence"
    t.integer "organization_id"
    t.string "plant_designer"
    t.string "plant_installer"
    t.string "plant_operator"
    t.string "portfolio"
    t.string "power_source_provision"
    t.string "recording_period"
    t.string "related_market_site"
    t.string "rnoc_notification_date"
    t.string "rnoc_tests_end_date"
    t.string "serial"
    t.string "severity"
    t.string "site_id"
    t.string "site_type_apcode"
    t.string "state"
    t.string "sub_types"
    t.string "tech_department"
    t.string "telco_area"
    t.string "test_results"
    t.string "timezone"
    t.string "type_of_plant"
    t.string "type_of_project"
    t.string "typical_use"
    t.datetime "updated_at", null: false
    t.string "uuid"
    t.string "warranty_expiration_date"
    t.index ["id"], name: "index_scada_sites_on_id"
  end

  create_table "scada_state_variables", force: :cascade do |t|
    t.string "apcode"
    t.datetime "created_at", null: false
    t.string "name"
    t.string "segment_id"
    t.datetime "updated_at", null: false
    t.string "uri"
    t.string "uuid"
  end

  create_table "sessions", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.string "ip_address"
    t.datetime "updated_at", null: false
    t.string "user_agent"
    t.bigint "user_id", null: false
    t.index ["user_id"], name: "index_sessions_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.string "email_address", null: false
    t.string "password_digest", null: false
    t.integer "role", default: 0, null: false
    t.datetime "updated_at", null: false
    t.index ["email_address"], name: "index_users_on_email_address", unique: true
  end

  add_foreign_key "sessions", "users"
end
