# db/migrate/20230626173058_create_projects.rb

class CreatePvsysts < ActiveRecord::Migration[7.0]
  def change
    create_table :pvsysts do |t|
      t.string :project
      t.string :version
      t.string :geographical_site
      t.string :situation_latitude
      t.string :situation_longitude
      t.string :time_defined_as
      t.string :time_zone
      t.string :altitude
      t.string :meteo_data
      t.string :country
      t.string :simulation_variant
      t.datetime :simulation_date
      # simlulation params
      t.integer :axis_tilt
      t.integer :axis_azimuth
      t.integer :minimum_phi
      t.integer :maximum_phi
      t.string :tracking_algorithm
      t.integer :number_of_trackers
      t.float :tracker_spacing
      t.float :collector_width
      t.float :phi_limits
      t.float :ground_cover_ratio
      t.string :models_used
      t.string :horizon
      t.string :near_shadings
      t.string :users_needs
      t.float :grid_power_limitation_active_power
      t.float :grid_power_limitation_pnom_ratio
      t.float :power_factor_cos
      t.float :power_factor_phi
      # pv array characteristics
      # pv module
      t.string :pv_module
      t.string :original_pysyst_db_manufacturer
      t.integer :pv_modules_in_series
      t.integer :pv_modules_in_parallel
      t.integer :total_pv_modules
      t.integer :module_unit_nom_power
      t.integer :global_power_nominal
      t.integer :global_power_operating_cond
      t.integer :u_mpp
      t.integer :i_mpp
      t.integer :module_area
      t.integer :cell_area
      # inverter
      t.string :inverter_model
      t.string :custom_params_def_manufacturer
      t.string :operating_voltage
      t.integer :inverter_unit_nom_power
      # pv array loss factors
      t.float :avg_loss_fraction
      t.float :array_soiling_losses_jan
      t.float :array_soiling_losses_feb
      t.float :array_soiling_losses_mar
      t.float :array_soiling_losses_apr
      t.float :array_soiling_losses_may
      t.float :array_soiling_losses_jun
      t.float :array_soiling_losses_jul
      t.float :array_soiling_losses_aug
      t.float :array_soiling_losses_sep
      t.float :array_soiling_losses_oct
      t.float :array_soiling_losses_nov
      t.float :array_soiling_losses_dec
      t.float :thermal_loss_factor_uc
      t.float :thermal_loss_factor_uv
      t.float :wiring_ohmic_loss_global_array_res
      t.float :wiring_ohmic_loss_fraction
      t.float :module_quality_loss_fraction
      t.float :module_mismatch_loss_fraction
      t.float :strings_mismatch_loss_fraction
      t.float :incidence_effect_0
      t.float :incidence_effect_30
      t.float :incidence_effect_55
      t.float :incidence_effect_60
      t.float :incidence_effect_65
      t.float :incidence_effect_70
      t.float :incidence_effect_75
      t.float :incidence_effect_80
      t.float :incidence_effect_90
      t.integer :grid_voltage
      t.integer :wires
      t.float :wires_loss_fraction
      t.integer :iron_loss
      t.float :iron_loss_fraction
      t.float :inductive_loss
      t.float :inductive_loss_fraction
      t.float :aux_loss_constant
      t.float :aux_loss_power_thresh
      t.float :night_aux_consumption
      # main system params
      t.string :system_type
      t.float :field_orientation_axis_tilt
      t.float :field_orientation_axis_azimuth
      t.string :pv_modules_model
      t.string :pv_modules_pnom_total
      t.integer :pv_array_number_modules
      t.integer :pv_array_pnom_total
      t.string :main_system_inverter_model
      t.integer :main_system_pnom
      t.float :main_system_inverter_pack
      t.integer :main_system_pnom_total
      t.float :user_needs_unlimited_load
      t.float :user_needs_cos_phi
      t.integer :main_simulation_produced_energy
      t.integer :main_simulation_specific_prod
      t.integer :main_simulation_aparent_energy
      t.float :main_simulation_perf_ratio
      # balances and main results
      t.float :main_globhor_jan
      t.float :main_globhor_feb
      t.float :main_globhor_mar
      t.float :main_globhor_apr
      t.float :main_globhor_may
      t.float :main_globhor_jun
      t.float :main_globhor_jul
      t.float :main_globhor_aug
      t.float :main_globhor_sep
      t.float :main_globhor_oct
      t.float :main_globhor_nov
      t.float :main_globhor_dec
      t.float :main_globhor_year
      t.float :main_diffhor_jan
      t.float :main_diffhor_feb
      t.float :main_diffhor_mar
      t.float :main_diffhor_apr
      t.float :main_diffhor_may
      t.float :main_diffhor_jun
      t.float :main_diffhor_jul
      t.float :main_diffhor_aug
      t.float :main_diffhor_sep
      t.float :main_diffhor_oct
      t.float :main_diffhor_nov
      t.float :main_diffhor_dec
      t.float :main_diffhor_year
      t.float :main_tamb_jan
      t.float :main_tamb_feb
      t.float :main_tamb_mar
      t.float :main_tamb_apr
      t.float :main_tamb_may
      t.float :main_tamb_jun
      t.float :main_tamb_jul
      t.float :main_tamb_aug
      t.float :main_tamb_sep
      t.float :main_tamb_oct
      t.float :main_tamb_nov
      t.float :main_tamb_dec
      t.float :main_tamb_year
      t.float :main_globinc_jan
      t.float :main_globinc_feb
      t.float :main_globinc_mar
      t.float :main_globinc_apr
      t.float :main_globinc_may
      t.float :main_globinc_jun
      t.float :main_globinc_jul
      t.float :main_globinc_aug
      t.float :main_globinc_sep
      t.float :main_globinc_oct
      t.float :main_globinc_nov
      t.float :main_globinc_dec
      t.float :main_globinc_year
      t.float :main_globeff_jan
      t.float :main_globeff_feb
      t.float :main_globeff_mar
      t.float :main_globeff_apr
      t.float :main_globeff_may
      t.float :main_globeff_jun
      t.float :main_globeff_jul
      t.float :main_globeff_aug
      t.float :main_globeff_sep
      t.float :main_globeff_oct
      t.float :main_globeff_nov
      t.float :main_globeff_dec
      t.float :main_globeff_year
      t.float :main_earray_jan
      t.float :main_earray_feb
      t.float :main_earray_mar
      t.float :main_earray_apr
      t.float :main_earray_may
      t.float :main_earray_jun
      t.float :main_earray_jul
      t.float :main_earray_aug
      t.float :main_earray_sep
      t.float :main_earray_oct
      t.float :main_earray_nov
      t.float :main_earray_dec
      t.float :main_earray_year
      t.float :main_egrid_jan
      t.float :main_egrid_feb
      t.float :main_egrid_mar
      t.float :main_egrid_apr
      t.float :main_egrid_may
      t.float :main_egrid_jun
      t.float :main_egrid_jul
      t.float :main_egrid_aug
      t.float :main_egrid_sep
      t.float :main_egrid_oct
      t.float :main_egrid_nov
      t.float :main_egrid_dec
      t.float :main_egrid_year
      t.float :main_pr_jan
      t.float :main_pr_feb
      t.float :main_pr_mar
      t.float :main_pr_apr
      t.float :main_pr_may
      t.float :main_pr_jun
      t.float :main_pr_jul
      t.float :main_pr_aug
      t.float :main_pr_sep
      t.float :main_pr_oct
      t.float :main_pr_nov
      t.float :main_pr_dec
      t.float :main_pr_year
      t.float :performance_ratio_jan
      t.float :performance_ratio_feb
      t.float :performance_ratio_mar
      t.float :performance_ratio_apr
      t.float :performance_ratio_may
      t.float :performance_ratio_jun
      t.float :performance_ratio_jul
      t.float :performance_ratio_aug
      t.float :performance_ratio_sep
      t.float :performance_ratio_oct
      t.float :performance_ratio_nov
      t.float :performance_ratio_dec
      t.float :lc_collection_loss_jan
      t.float :lc_collection_loss_feb
      t.float :lc_collection_loss_mar
      t.float :lc_collection_loss_apr
      t.float :lc_collection_loss_may
      t.float :lc_collection_loss_jun
      t.float :lc_collection_loss_jul
      t.float :lc_collection_loss_aug
      t.float :lc_collection_loss_sep
      t.float :lc_collection_loss_oct
      t.float :lc_collection_loss_nov
      t.float :lc_collection_loss_dec
      t.float :ls_system_loss_jan
      t.float :ls_system_loss_feb
      t.float :ls_system_loss_mar
      t.float :ls_system_loss_apr
      t.float :ls_system_loss_may
      t.float :ls_system_loss_jun
      t.float :ls_system_loss_jul
      t.float :ls_system_loss_aug
      t.float :ls_system_loss_sep
      t.float :ls_system_loss_oct
      t.float :ls_system_loss_nov
      t.float :ls_system_loss_dec
      t.float :yf_produced_useful_jan
      t.float :yf_produced_useful_feb
      t.float :yf_produced_useful_mar
      t.float :yf_produced_useful_apr
      t.float :yf_produced_useful_may
      t.float :yf_produced_useful_jun
      t.float :yf_produced_useful_jul
      t.float :yf_produced_useful_aug
      t.float :yf_produced_useful_sep
      t.float :yf_produced_useful_oct
      t.float :yf_produced_useful_nov
      t.float :yf_produced_useful_dec
      t.float :yf_produced_useful_year

      t.timestamps
    end
  end
end
